server:
  port: 8762
  tomcat:
    uri-encoding: UTF-8
    
spring:
  application:
    name: eureka-service
  messages:
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  banner:
    charset: UTF-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/